trainer:
  master_port: "39533"
  devices: "0"
  gpus: [0]
  seed: 1234
  acc_step: 4
  accelerator: ddp
  precision: 32
  batch_size: 600 
  max_epochs: 100
  ur90_path: /share/hongliang/ur90_201803.pkl 

model:
  resume: True
  ckpt_path: ./cpu_mudel/fastmsa-cpu.ckpt 

callback:
  monitor: val_acc
  dirpath: ./model_uni/
  filename: pl_biencoder-{epoch:03d}-{val_acc:.4f}
  mode: max
  save_top_k: 5
  save_on_train_epoch_end: True

logger:
  log_every_n_steps: 10
  use_wandb: False
  project: uniclust_pl
  log_model: False